version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    depends_on:
      - postgresql
      - redis
    volumes:
      - ../../:/app
    ports:
      - '8888:8080'
    networks:
      - docker-practice-net

  postgresql:
    image: postgres:15.0-alpine
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
    networks:
      - docker-practice-net
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0.5-alpine
    networks:
      - docker-practice-net
    ports:
      - '6379:6379'

networks:
  docker-practice-net:
    
